### ISSUE TITLE
swift2.0 compatibility

### ISSUE THREAD

**Issue by sagdusmir** [namanhams/Swift-UIImageView-AFNetworking#2]
Are there any plans to make this available for swift2.0?

**Comment by namanhams** [comment]
Thanks for your feedback. I'll do in 1-2 days.

**Comment by namanhams** [comment]
Hi,
Sorry for late reply.
There's new branch "XCode 7 beta" that has been tested with Swift 2.0 in XCode 7. You can try out.

**Comment by sagdusmir** [comment]
Thanks!

I got the old code working with just a few tweaks - but I will definitely give the "official" version a try.  :)
