### ISSUE TITLE
Is there a MAX Size on the cache?

### ISSUE THREAD

**Issue by goelv** [namanhams/Swift-UIImageView-AFNetworking#4]
Am I able to set it or reset the cache?

By the way, this library is very useful and it works like a charm.. thanks a lot for sharing this.

**Comment by namanhams** [comment]
@goelv : there're 2 ways to do it. First way, you can create your own cache and then pass to setSharedImageCache. The other way, is you can cast the object returned by sharedImageCache() to NSCache, and then use the NSCache functions. This is kind of hacky way. I prefer the first way.

**Comment by goelv** [comment]
thanks @namanhams i will check this out.
