### ISSUE TITLE
how long is the Cache Object being stored?

### ISSUE THREAD

**Issue by goelv** [namanhams/Swift-UIImageView-AFNetworking#6]
It seems like the cache is getting reset every time the app is being run? The cache does not persist between successive sessions of the app? I'm trying to use the app in quick successions to see if the images downloaded & stored in cache are no longer being re-downloaded from the server.

**Comment by namanhams** [comment]
@goelv : if you look at the source code, i use a default cache which is a AFImageCache object, which is actually a NSCache. NSCache is in-memory cache, it's not disk cache. You can use a different cache object, as long as it conforms to AFImageCacheProtocol. It's not very hard to make one anyway.

**Comment by goelv** [comment]
thanks for the quick response @namanhams 

Could you show me how that would be done using your existing source code?
